

## Project information
site_name: nukoDocs
site_description: Documents for nukoyama
site_author: nukoyama
site_url: https://nukoyama.github.io/mkdocs-test/

## Repository
repo_name: nukoyama/mkdocs-test
repo_url: https://github.com/nukoyama/mkdocs-test

## Copyright
copyright: Copyright &copy; 2020 nukoyama

# Google Analytics
google_analytics:
  - UA-165061642-1
  - auto

# theme: mkdocs
# theme: readthedocs
# theme: material
# theme: rtd-dropdown
# theme: ivory

theme:
  name: material
  custom_dir: overrides
  language: ja
  features:
    - navigation.tabs
    - navigation.expand
    ## instantはonにしないこと。
    ## mathjaxをrenderしなくなる。
    ##   - instant
  palette:
    primary: teal # default: indigo
    accent: teal
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
    # favicon: material/library
  # logo: images/logo.svg
  # favicon: images/favicon.png


nav:
  - Home: index.md
  - welcome.md
  - test.md
  - sub:
    - test 11: sub/1-test.md
    - test 2: sub/2-test.md
    - test 3: sub/3-test.md
    - subsub:
      - test 3: sub/subsub/3-test.md
      - test 4: sub/subsub/4-test.md
      - sub/subsub/5-test.md
  - MkDocs:
    - mkdocs/index.md
    - mkdocs/issue.md
    - mkdocs/extension.md
    - mkdocs/plugin.md
    - mkdocs/custom-css.md
    - mkdocs/custom-theme.md
    - mkdocs/math.md
  - LaTeX:
    - LaTeX Tutorial:
      - tex/tutorial01.md
      - tex/tutorial02.md
      - tex/tutorial03.md
      - tex/tutorial04.md
    - kaishi:
      - tex/kaishi01.md
      - tex/kaishi02.md
      - tex/kaishi03.md
    - Others:
      - tex/latexmk.md


# Extras
extra:
  social:
    - icon: fontawesome/brands/github # or github-alt
      link: https://github.com/nukoyama
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/geniusium_
    # - icon: fontawesome/brands/linkedin
    #   link: https://linkedin.com/in/squidfunk
  disqus: mkdocs-test-1
  # disqus: # disabled by empty value


markdown_extensions:
  ## table of comtents
  - toc:
      permalink: "#" # any string
      baselevel: 2
      separator: "_"
  ## pymdownx
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false #? does not work
      ordinal_numbers: false
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys
  ## Material
  - admonition
  - footnotes
  - codehilite
  - meta
  ## MkDocs+
  - fontawesome_markdown
  ## others
  - def_list # 定義リスト
  - mdx_truly_sane_lists # tab spaces: 4 (default) -> 2
  # - markdown_katex: # KaTeX
  #     no_inline_svg: True
  #     insert_fonts_css: True
  - attr_list # リンクを新規タブで開く


plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: datetime
      time_zone: Asia/Tokyo


extra_css:
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - css/header-awesome.css

extra_javascript:
  ## mathjax version 3
  - js/mathjax3-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  ## mathjax version 2
  ## v2 の config は /overrides/main.html に直接記述。
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
